/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version "8.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("io.javalin:javalin:6.3.0")

    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "mcobserver.backend.MCObserver"
}

sourceSets {
   main {
      resources {
         srcDirs("src/main/resources")
      }
   }
}

tasks {
    named<ShadowJar>("shadowJar") {
        archiveFileName.set("MCObserver.jar")
        mergeServiceFiles()
        manifest {
            attributes(mapOf("Main-Class" to "mcobserver.backend.MCObserver"))
        }
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
}
